[package]
name = "pshenmic_dpp_token_configuration_change_item"
edition = "2024"
version.workspace = true

[dependencies]
dpp = { workspace = true, features = ["state-transition-serde-conversion"] }
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
pshenmic_dpp_token_configuration = {path = "../token_configuration"}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_identifier = {path = "../identifier"}
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
