[package]
name = "pshenmic_dpp_document"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_identifier = { path = "../identifier" }
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_data_contract = {path = "../data_contract"}
dpp = { workspace = true, features = [
    "document-value-conversion"
]}
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }