[package]
name = "pshenmic_dpp_document"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_data_contract = {path = "../data_contract"}
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "document-value-conversion"
]}
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }