[package]
name = "pshenmic_dpp_token_configuration"
edition = "2024"
version.workspace = true

[dependencies]
dpp = { workspace = true, features = ["state-transition-serde-conversion"] }
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
pshenmic_dpp_identifier = { path = "../identifier" }