[package]
name = "pshenmic_dpp_token_configuration"
edition = "2024"
version.workspace = true

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
dpp = { workspace = true, features = ["state-transition-serde-conversion"] }
pshenmic_dpp_identifier = { path = "../identifier" }
pshenmic_dpp_utils = { path = "../utils" }
serde-wasm-bindgen = { workspace = true }
pshenmic_dpp_enums = { path = "../enums" }