[package]
name = "pshenmic_dpp_token_configuration"
edition = "2024"
version.workspace = true

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = ["state-transition-serde-conversion"] }
pshenmic_dpp_identifier = { path = "../identifier" }
pshenmic_dpp_utils = { path = "../utils" }
pshenmic_dpp_enums = { path = "../enums" }
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
js-sys = "0.3.53"