[package]
name = "pshenmic_dpp_identity"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
dpp = { path = "../../../../platform/packages/rs-dpp", default-features = false}
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
pshenmic_dpp_public_key = { path = "../public_key" }

[profile.release]
lto = true
opt-level = 'z'