[package]
name = "pshenmic_dpp_identity"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = [
    "identity-serialization"
]}
pshenmic_dpp_identity_public_key = { path = "../identity_public_key" }
pshenmic_dpp_identifier = { path = "../identifier" }
pshenmic_dpp_utils = { path = "../utils" }
