[workspace]
resolver = "2"
members = ["packages/document", "packages/document_batch", "packages/cbor-conversation", "packages/enums", "packages/mock_bls", "packages/private_key", "packages/public_key", "packages/utils"]

[lib]
crate-type = ["cdylib", "lib"]

[package]
name = "pshenmic-dpp"
version = "1.0.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
bincode = {version = "=2.0.0-rc.3"}
bincode_derive = {version = "=2.0.0-rc.3"}
pshenmic_dpp_document_batch = {path = "packages/document_batch"}
pshenmic_dpp_document_search = {path = "packages/cbor-conversation" }