[package]
name = "pshenmic-dpp"
authors = ["owl352 <kokosinca123@gmail.com>"]
version = "2.0.0-dev.1"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
dpp = { git = "https://github.com/owl352/platform", rev = "3f13188", default-features = false, features = [
    "identity-value-conversion",
    "identity-serialization"
] }
drive = { git = "https://github.com/owl352/platform", rev = "3f13188", default-features = false }
napi = {version = "3.7.0", features = ["napi3"], default-features = false}
napi-derive = "3.4.0"

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = "fat"
opt-level = "z"
strip = "symbols"
codegen-units = 1
panic = "abort"
incremental = false
debug = false
