[package]
name = "pshenmic_dpp_data_contract"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_enums = {path = "../enums"}
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "data-contract-json-conversion",
    "platform-value"
]}
js-sys = "0.3.53"
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
