[package]
name = "pshenmic_dpp_data_contract"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_token_configuration = {path = "../token_configuration"}
pshenmic_dpp_identifier = { path = "../identifier" }
dpp = { workspace = true, features = [
    "data-contract-json-conversion",
]}
js-sys = { workspace = true }
serde-wasm-bindgen = { workspace = true }
