[package]
name = "pshenmic_dpp_identifier"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = []}
pshenmic_dpp_utils = { path = "../utils" }
