[package]
name = "pshenmic_dpp_identifier"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
dpp = { workspace = true, features = []}
pshenmic_dpp_utils = { path = "../utils" }
