[package]
name = "pshenmic_dpp_consensus_error"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = [
    "platform-value",
]}
pshenmic_dpp_utils = {path = "../utils"}
