[package]
name = "pshenmic_dpp_enums"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "state-transitions"
]}
