[package]
name = "pshenmic_dpp_enums"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
dpp = { workspace = true, features = [
    "state-transitions"
]}
