[package]
name = "pshenmic_dpp_enums"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = "0.2.100"
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "identity-value-conversion",
]}

[profile.release]
lto = true
opt-level = 'z'