[package]
name = "pshenmic_dpp_encrypted_note"
edition = "2024"
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = ["document-json-conversion"] }
