[package]
name = "pshenmic_dpp_identity_transitions"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
dpp = { path = "../../../../platform/packages/rs-dpp", default-features = false, features = [
    "state-transition-signing"
]}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_public_key = {path = "../public_key"}
pshenmic_dpp_state_transition = {path = "../state_transition"}
pshenmic_dpp_enums = {path = "../enums"}

[profile.release]
lto = true
opt-level = 'z'