[package]
name = "pshenmic_dpp_asset_lock_proof"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = [
    "state-transition-signing"
]}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_identifier = {path = "../identifier"}
pshenmic_dpp_enums = {path = "../enums"}
js-sys = { workspace = true }
serde-wasm-bindgen = { workspace = true }
serde = { version = "1.0.197", features = ["derive"] }
hex = "0.4.3"
serde_json = { version = "1.0", features = ["preserve_order"] }