[package]
name = "pshenmic_dpp_document_search"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "cbor",
]}
pshenmic_dpp_utils = {path = "../utils"}
base64 = "0.22.1"
ciborium = "0.2.2"
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
