[package]
name = "pshenmic_dpp_mock_bls"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
dpp = { workspace = true, features = [
    "bls-signatures",
]}