[package]
name = "pshenmic_dpp_masternode_vote"
edition = "2024"
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = [
    "state-transition-signing"
]}
js-sys = "0.3.53"
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_identifier = {path = "../identifier" }
pshenmic_dpp_state_transition = {path = "../state_transition"}
pshenmic_dpp_asset_lock_proof = {path = "../asset_lock_proof"}