[package]
name = "pshenmic_dpp_identity_public_key"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
dpp = { workspace = true, features = [
    "identity-value-conversion",
]}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_contract_bounds = {path = "../contract_bounds"}
pshenmic_dpp_utils = {path = "../utils"}