[package]
name = "pshenmic_dpp_documents_batch"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
pshenmic_dpp_document = {path = "../document"}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_state_transition = {path = "../state_transition"}
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "document-json-conversion",
]}
js-sys = "0.3.77"
serde-wasm-bindgen = { git = "https://github.com/QuantumExplorer/serde-wasm-bindgen", branch = "feat/not_human_readable" }
