[package]
name = "pshenmic_dpp_private_key"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
dpp = { workspace = true, features = [
    "identity-value-conversion",
]}
pshenmic_dpp_enums = {path = "../enums"}
