[package]
name = "pshenmic_dpp_private_key"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "identity-value-conversion",
]}
