[package]
name = "pshenmic_dpp_document_batch"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", features = ["serde-serialize"] }
pshenmic_dpp_document = {path = "../document"}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_state_transition = {path = "../state_transition"}
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "document-json-conversion",
]}
