[package]
name = "pshenmic_dpp_group_state_transition_info"
edition = "2024"
version.workspace = true

[dependencies]
dpp = { workspace = true, features = ["document-json-conversion"] }
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
pshenmic_dpp_identifier = {path = "../identifier"}
