[package]
name = "pshenmic_dpp_group_state_transition_info"
edition = "2024"
version.workspace = true

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = ["document-json-conversion"] }
pshenmic_dpp_identifier = {path = "../identifier"}
