[package]
name = "pshenmic_dpp_data_contract_transitions"
version.workspace = true
edition = "2024"

[dependencies]
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
dpp = { git = "https://github.com/dashpay/platform", branch = "master", default-features = false, features = [
    "state-transition-signing"
]}
pshenmic_dpp_data_contract = {path = "../data_contract"}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_state_transition = {path = "../state_transition"}
