[package]
name = "pshenmic_dpp_data_contract_transitions"
version.workspace = true
edition = "2024"

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = [
    "state-transition-signing"
]}
pshenmic_dpp_data_contract = {path = "../data_contract"}
pshenmic_dpp_enums = {path = "../enums"}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_state_transition = {path = "../state_transition"}
