[package]
name = "pshenmic_dpp_contract_bounds"
edition = "2024"
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
dpp = { workspace = true, features = [
    "state-transition-signing"
]}
pshenmic_dpp_identifier = {path = "../identifier" }