[package]
name = "pshenmic_dpp_state_transition"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { version = "=0.2.100", default-features = false, features = ["serde-serialize"] }
pshenmic_dpp_public_key = {path = "../identity_public_key" }
pshenmic_dpp_private_key = {path = "../private_key"}
pshenmic_dpp_utils = {path = "../utils"}
pshenmic_dpp_identifier = {path = "../identifier"}
pshenmic_dpp_mock_bls = {path = "../mock_bls"}
pshenmic_dpp_enums = {path = "../enums"}
dpp = { workspace = true, features = [
    "state-transition-signing",
    "platform-value"
]}
sha2 = "0.10.8"
