[package]
name = "pshenmic_dpp_utils"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }
dpp = { workspace = true, features = [
    "platform-value",
    "document-json-conversion"
] }
serde_json = { version = "1.0", features = ["preserve_order"] }
