[package]
name = "pshenmic_dpp_utils"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = { workspace = true, features = ["serde-serialize"] }
anyhow = { version = "1.0.75" }
dpp = { workspace = true, features = [
    "platform-value",
    "document-json-conversion"
] }
js-sys = "0.3.53"
serde_json = { version = "1.0", features = ["preserve_order"] }
