name: Build & Test

on:
  push:
    branches: [ "master", "v1.1.0-dev", "v1.1.0", "v2.0.0-dev" ]
  pull_request:
    branches: [ "master", "v1.1.0-dev", "v1.1.0", "v2.0.0-dev" ]

jobs:
  build:
    name: Build ${{ matrix.settings.target }} (Node ${{ matrix.node-version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        settings:
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager --install "ndk;27.1.12297006"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1-threads, x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, aarch64-linux-android x86_64-linux-android, aarch64-apple-ios-sim aarch64-apple-darwin x86_64-apple-darwin
          components: rustfmt

      - name: Install cargo-zigbuild
        run: |
          rustup component add rust-src
          cargo install cargo-zigbuild

      - name: Install LLVM for WebAssembly (macOS)
        run: |
          brew install llvm
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Install project dependencies & Wasm tools
        run: |
          yarn install
          cargo install wasm-bindgen-cli@0.2.105 wasm-opt

      - name: Build JS bundle
        run: yarn build:full
        env:
          CARGO_BUILD_TARGET: ${{ matrix.settings.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ matrix.settings.target }}-${{ matrix.node-version }}
          path: |
            ./dist

  test:
    name: Test ${{ matrix.settings.target }} (Node ${{ matrix.node-version }})
    needs: build
    runs-on: ${{ matrix.settings.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.x, 24.x]
        settings:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-${{ matrix.settings.target }}-${{ matrix.node-version }}
          path: .

      - name: Setup QEMU
        if: runner.os == 'Linux' && contains(matrix.settings.target, 'aarch64')
        uses: docker/setup-qemu-action@v3

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager --install "ndk;27.1.12297006"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.settings.target }}, wasm32-wasip1-threads
          components: rustfmt

      - name: Install cargo-zigbuild
        run: |
          rustup component add rust-src
          cargo install cargo-zigbuild

      - name: Install LLVM for WebAssembly (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install llvm
          echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV
          sudo apt-get update
          sudo apt-get install -y gcc-multilib musl-tools pkg-config libssl-dev
          echo "OPENSSL_INCLUDE_DIR=/usr/include/x86_64-linux-gnu" >> $GITHUB_ENV

      - name: Install Mobile Rust targets (Linux & macOS)
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          rustup target add aarch64-linux-android x86_64-linux-android || true
        shell: bash

      - name: Install iOS Rust target (macOS only)
        if: runner.os == 'macOS'
        run: rustup target add aarch64-apple-ios-sim aarch64-apple-darwin x86_64-apple-darwin || true

      - name: Install project dependencies & Wasm tools
        run: |
          yarn install
          cargo install wasm-bindgen-cli@0.2.105 wasm-opt

      - name: Run tests
        run: yarn test
