name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Add rustup WASM target
      run: |
        rustup target add wasm32-unknown-unknown

    - name: Check Rust code linting rules
      run: |
        rust fmt --check

    - name: Install dependencies
      run: |
        yarn

    - name: Build JS bundle
      run: |
        yarn build:full
