name: Publish package to NPM
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Add rustup WASM target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Check Rust code linting rules
        run: |
          cargo fmt --check

      - name: Install Rust dependencies for WASM
        run: |
          cargo install wasm-bindgen-cli@0.2.100 wasm-opt
          cargo install wasm-pack

      - name: Install dependencies
        run: |
          yarn

      - name: Build JS bundle
        run: |
          yarn build:full

      - name: Publish package to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
